# Generated by Django 5.0.6 on 2024-05-24 04:45

import django.utils.timezone
from django.db import migrations, models
from django.core.exceptions import ObjectDoesNotExist


# migrate时在数据库中创建6个房间
def create_rooms(apps, schema_editor):
    Room = apps.get_model('hotel', 'Room')
    print(123)
    for i in range(1, 7):
        try:
            Room.objects.get(room_id=i)
        except ObjectDoesNotExist:
            Room.objects.create(room_id=i)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='请求时间')),
                ('room_id', models.IntegerField(default=1, verbose_name='房间号')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='入住时间')),
                ('request_type', models.IntegerField(choices=[(0, 'turn on/off'), (1, 'increase temp'), (2, 'decrease temp'), (3, 'increase speed'), (4, 'decrease speed')], default=0, verbose_name='请求类型')),
                ('current_temp', models.FloatField(default=25.0, verbose_name='温度')),
                ('fan_speed', models.IntegerField(choices=[(3, 'HIGH'), (2, 'MIDDLE'), (1, 'LOW')], default=2, verbose_name='风速')),
                ('fee', models.FloatField(default=0.0, verbose_name='费用')),
                ('fee_rate', models.FloatField(default=0.3, verbose_name='当前费率')),
                ('on', models.BooleanField(default=False, verbose_name='空调是否开启')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='房间号')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='入住时间')),
                ('current_temp', models.FloatField(default=25.0, verbose_name='当前温度')),
                ('fan_speed', models.IntegerField(choices=[(3, 'HIGH'), (2, 'MIDDLE'), (1, 'LOW')], default=2, verbose_name='风速')),
                ('fee', models.FloatField(default=0.0, verbose_name='费用')),
                ('on', models.BooleanField(default=False, verbose_name='空调是否开启')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='房间是否有人入住')),
                ('fee_rate', models.FloatField(default=0.3, verbose_name='当前费率')),
            ],
        ),
        migrations.RunPython(create_rooms),
    ]
