# Generated by Django 5.0.6 on 2024-05-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_room_fan_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.IntegerField(choices=[(0, 'turn on/off'), (1, 'increase temp'), (2, 'decrease temp'), (3, 'increase speed'), (4, 'decrease speed'), (5, 'check in'), (6, 'check out'), (7, 'set speed')], default=-1, verbose_name='请求类型'),
        ),
        migrations.AlterField(
            model_name='room',
            name='fan_speed',
            field=models.IntegerField(choices=[(3, 'HIGH'), (2, 'MIDDLE'), (1, 'LOW')], default=2, verbose_name='风速'),
        ),
    ]
